/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anderson;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;


import java.util.Scanner;


/**
 * Help Screen
 * @author 10027
 */
public class HelpScreen extends javax.swing.JFrame {


    
    public String[] helpArr = new String[10];
    public int size = 0;
    public int pos = 0;

    public HelpScreen() {
        initComponents();
        
        try
        {
            Scanner sc = new Scanner(new File("Help.txt"));
            
            while(sc.hasNext())
            {
                helpArr[size] = sc.nextLine();
                size++;
            }
            
            
        } catch (FileNotFoundException ex)
        {
            System.out.println("Fle not found");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        lblHelpScreen = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnTutorial = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        pnlMessage = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setLayout(null);

        btnClose.setBackground(new java.awt.Color(51, 51, 51));
        btnClose.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);
        btnClose.setBounds(660, 30, 77, 30);

        lblHelpScreen.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblHelpScreen.setForeground(new java.awt.Color(255, 255, 255));
        lblHelpScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelpScreen.setText("Help Screen");
        jPanel1.add(lblHelpScreen);
        lblHelpScreen.setBounds(210, 30, 366, 30);

        btnNext.setBackground(new java.awt.Color(51, 51, 51));
        btnNext.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.setActionCommand("1");
        btnNext.setBorder(null);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCycle(evt);
            }
        });
        jPanel1.add(btnNext);
        btnNext.setBounds(620, 80, 110, 80);

        btnTutorial.setBackground(new java.awt.Color(51, 51, 51));
        btnTutorial.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnTutorial.setForeground(new java.awt.Color(255, 255, 255));
        btnTutorial.setText("Tutorial Video ");
        btnTutorial.setBorder(null);
        btnTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnTutorial);
        btnTutorial.setBounds(50, 200, 110, 80);

        btnPrevious.setBackground(new java.awt.Color(51, 51, 51));
        btnPrevious.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("Previous");
        btnPrevious.setActionCommand("-1");
        btnPrevious.setBorder(null);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCycle(evt);
            }
        });
        jPanel1.add(btnPrevious);
        btnPrevious.setBounds(50, 90, 110, 80);

        txtTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("How to check High Scores");
        jPanel1.add(txtTitle);
        txtTitle.setBounds(230, 80, 310, 40);

        txtArea.setColumns(20);
        txtArea.setLineWrap(true);
        txtArea.setRows(5);
        txtArea.setText("The High Score Screen can be accessed on the Main Screen.");
        pnlMessage.setViewportView(txtArea);

        jPanel1.add(pnlMessage);
        pnlMessage.setBounds(203, 143, 380, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, -10, 780, 450);

        setSize(new java.awt.Dimension(734, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        new MainScreen().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutorialActionPerformed
        try {
            Desktop.getDesktop().open(new File("Tutorial.mov"));
            
        } catch (IOException ex) {
            System.out.println("File not found");
        }
        
    }//GEN-LAST:event_btnTutorialActionPerformed

    private void btnCycle(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCycle
    {//GEN-HEADEREND:event_btnCycle
        int i = Integer.parseInt(evt.getActionCommand());
        pos += i;
        
        if (pos > 9) pos = 0;      
        if (pos < 0) pos = 9;  
        
        String[] s = helpArr[pos].split("#");
        
        txtTitle.setText(s[0]);
        txtArea.setText(s[1]);
    }//GEN-LAST:event_btnCycle


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnTutorial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHelpScreen;
    private javax.swing.JScrollPane pnlMessage;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
