/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anderson;

/**
 * Level Select Screen
 * @author Kian
 */
public class LevelSelectScreen extends javax.swing.JFrame
{

    UserArray user = new UserArray();

    /**
     * Creates new form LevelSelectScreen
     */
    public LevelSelectScreen()
    {
        initComponents();
        if (!user.getBestTimes(0, 1).equals("Not completed"))
        {

        }
        if (!user.getBestTimes(0, 2).equals("Not completed"))
        {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLevel1 = new javax.swing.JLabel();
        lblLevel2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblLevel3 = new javax.swing.JLabel();
        btnLvl3 = new javax.swing.JButton();
        btnLvl2 = new javax.swing.JButton();
        btnLvl1 = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Level Select");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblLevel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLevel1.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel1.setText("Level 1");

        lblLevel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLevel2.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel2.setText("Level 2");

        lblTitle.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Level Select");

        lblLevel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLevel3.setForeground(new java.awt.Color(255, 255, 255));
        lblLevel3.setText("Level 3");

        btnLvl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anderson/Images/level3.png"))); // NOI18N
        btnLvl3.setActionCommand("3");
        btnLvl3.setBorder(null);
        btnLvl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLvlActionPerformed(evt);
            }
        });

        btnLvl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anderson/Images/level2.png"))); // NOI18N
        btnLvl2.setToolTipText("");
        btnLvl2.setActionCommand("2");
        btnLvl2.setBorder(null);
        btnLvl2.setFocusCycleRoot(true);
        btnLvl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLvlActionPerformed(evt);
            }
        });

        btnLvl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anderson/Images/level1.png"))); // NOI18N
        btnLvl1.setActionCommand("1");
        btnLvl1.setBorder(null);
        btnLvl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLvlActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(51, 51, 51));
        btnClose.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnLvl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLvl2)
                .addGap(227, 227, 227)
                .addComponent(btnLvl3)
                .addGap(351, 351, 351))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(lblLevel1)
                .addGap(527, 527, 527)
                .addComponent(lblLevel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLevel3)
                .addGap(484, 484, 484))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLvl3)
                    .addComponent(btnLvl2)
                    .addComponent(btnLvl1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLevel1)
                    .addComponent(lblLevel2)
                    .addComponent(lblLevel3))
                .addContainerGap(584, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 2060, 1200);

        setSize(new java.awt.Dimension(1931, 1121));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLvlActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLvlActionPerformed
    {//GEN-HEADEREND:event_btnLvlActionPerformed
        String lvl = evt.getActionCommand();

        if (!user.getBestTimes(0, Integer.parseInt(lvl) - 1).equals("Not completed"))
        {
            switch (lvl)
            {
                case "1":
                    Level1Screen m1 = new Level1Screen();
                    Thread t1 = new Thread(m1);
                    t1.start();
                    m1.setVisible(true);
                    this.dispose();
                    break;

                case "2":
                        Level2Screen m2 = new Level2Screen();
                        Thread t2 = new Thread(m2);
                        t2.start();
                        m2.setVisible(true);
                        this.dispose();
                    break;

                case "3":
                        Level3Screen m3 = new Level3Screen();
                        Thread t3 = new Thread(m3);
                        t3.start();
                        m3.setVisible(true);
                        this.dispose();
                    break;
            }
            
            
        }


    }//GEN-LAST:event_btnLvlActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        new MainScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LevelSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LevelSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LevelSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LevelSelectScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LevelSelectScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLvl1;
    private javax.swing.JButton btnLvl2;
    private javax.swing.JButton btnLvl3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLevel1;
    private javax.swing.JLabel lblLevel2;
    private javax.swing.JLabel lblLevel3;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
