/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anderson;


public class MainScreen extends javax.swing.JFrame
{


    public MainScreen()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        txtMainScreen = new javax.swing.JLabel();
        txtHelp = new javax.swing.JLabel();
        lblBestTime = new javax.swing.JLabel();
        txtLevelSelect = new javax.swing.JLabel();
        btnBestTime = new javax.swing.JButton();
        btnLevelSelect = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setPreferredSize(new java.awt.Dimension(1934, 1121));
        getContentPane().setLayout(null);

        pnlBackground.setBackground(new java.awt.Color(0, 0, 0));
        pnlBackground.setLayout(null);

        txtMainScreen.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        txtMainScreen.setForeground(new java.awt.Color(255, 255, 255));
        txtMainScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMainScreen.setText("Main Screen");
        pnlBackground.add(txtMainScreen);
        txtMainScreen.setBounds(35, 104, 1900, 58);

        txtHelp.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtHelp.setForeground(new java.awt.Color(255, 255, 255));
        txtHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHelp.setText("Help");
        pnlBackground.add(txtHelp);
        txtHelp.setBounds(1410, 420, 180, 40);

        lblBestTime.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lblBestTime.setForeground(new java.awt.Color(102, 102, 102));
        lblBestTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBestTime.setText("Best Time");
        pnlBackground.add(lblBestTime);
        lblBestTime.setBounds(280, 420, 290, 43);

        txtLevelSelect.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtLevelSelect.setForeground(new java.awt.Color(255, 255, 255));
        txtLevelSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLevelSelect.setText("Level Select");
        pnlBackground.add(txtLevelSelect);
        txtLevelSelect.setBounds(840, 430, 260, 43);

        btnBestTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anderson/Images/level1.png"))); // NOI18N
        btnBestTime.setActionCommand("3");
        btnBestTime.setBorder(null);
        btnBestTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        pnlBackground.add(btnBestTime);
        btnBestTime.setBounds(250, 330, 350, 350);

        btnLevelSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anderson/Images/level2.png"))); // NOI18N
        btnLevelSelect.setActionCommand("1");
        btnLevelSelect.setBorder(null);
        btnLevelSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        pnlBackground.add(btnLevelSelect);
        btnLevelSelect.setBounds(800, 330, 350, 350);

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anderson/Images/level3.png"))); // NOI18N
        btnHelp.setActionCommand("2");
        btnHelp.setBorder(null);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        pnlBackground.add(btnHelp);
        btnHelp.setBounds(1330, 320, 350, 350);

        getContentPane().add(pnlBackground);
        pnlBackground.setBounds(-10, -10, 1970, 1160);

        setSize(new java.awt.Dimension(1952, 1168));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHelpActionPerformed
    {//GEN-HEADEREND:event_btnHelpActionPerformed
        if (evt.getActionCommand().equals("2"))
            new HelpScreen().setVisible(true);
            
        if (evt.getActionCommand().equals("3"))
            new BestTimeScreen().setVisible(true);
        
        if (evt.getActionCommand().equals("1"))
            new LevelSelectScreen().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnHelpActionPerformed


    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBestTime;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLevelSelect;
    private javax.swing.JLabel lblBestTime;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JLabel txtHelp;
    private javax.swing.JLabel txtLevelSelect;
    private javax.swing.JLabel txtMainScreen;
    // End of variables declaration//GEN-END:variables
}
